source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem "decent_exposure"
gem "haml"
gem "jquery-rails"
gem "json"
gem "typhoeus"

group :assets do
  gem "coffee-rails", "~> 3.1"
  gem "sass-rails", "~> 3.1"
  gem "uglifier"
end

group :development, :test do
  gem "capybara"
  gem "fabrication"
  gem "mocha"
  gem "rspec-rails"
  gem "shoulda"
  gem "spork", "~> 0.9.0.rc"
  gem "watchr"
end

