defaults: &defaults
  default_sms_service: smsout
  
  smsout_base_url: http://www.smsout.de/client/sendsms.php
  smsout_smstype: V1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults